# Generated by Django 4.2 on 2023-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_remove_profile_email_remove_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/default-avatar.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='header',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
